[package]
name = "echo_benchmark"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.32", features = ["full"] }
clap = { version = "4.4", features = ["derive"] }
rand = "0.8"
sysinfo = "0.29"
